language: dart
dart:
# Install the latest stable release
- dev
dart_task:
- dartanalyzer: true
- test: --platform vm

script:
- pub run dart_codecov_generator --report-on=lib/ --no-html   --verbose
- bash <(curl -s https://codecov.io/bash)
